language: node_js
node_js:
  - 10

cache:
  directories:
    - node_modules

before_script:
  - cd client
  - yarn install

deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-frontend
  api_key:
    secure: qBk+cKUaslt++/z+y6XeuizT0NDfVjiQ7eqa74Fenn9fCIhcsX/kXUzuUEjq8MJrif0Yv7lO3IClga1/tHbXcpYBBa5JPmXU5UdzvtOwg6L85KtQo3JQZqWQO2wcGg0p1VlIzt+Iyd3XPeSqCu1uguPCrtizd+pGPvGdfIPkyP4MrafNqXVAe19xVBlQx7VkqANEmUFyMeOLTttQe07hsAxtFhfXA3QhEhJbObWWW06pGUjsQWhRtBRqDDI3xvi4W2AINJiEz170CM/MFcgWyvE69JdWmZOkJ0dsS1Rv23I6MTNaTpdqlp51R4MsSoR915min8UTiq7zW8vnNk6cmgLSVtYZRmu+cLVQ2WxlLWmnA+UHTX49E73r6NS3+M/MfpU/I4R+MwBiF2LgipNjrp4wrNpgbxJMhmwX6B0x3Qmw91YSTfX2dChaZb6S2yO0yL8rJBOqcYz397iFAaqz+Zdwf1+mTlRrtbnDn08X1ahIF/Roi4kK0qBY+NWosZyvJj3OT0lJL5Tuxs/O8bH7naUuwpry7n7BpDLLEkZNflXEylj9XFnlHt2wYUO5uEDEi2idgGcA5TDL7K1k8iVdXZaTZeD2yTUjI2pbIlp+d+Q9ccsBJbY/hRV1oQREnDigr7C8qO4WGkFpCKoVD7tCXRjyqWjmuSXrAH2dYVaewP8=
