language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
before_script:
- cd client
- yarn install
deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-frontend
  api_key:
    secure: SL6maEYqecNXpsUEVCknMAt1etmeL9H5fJyg3dgYDiFDvaJRNbexbNVwutk5SdPlzZic3Ov1WIZTCHp4GEeWZEVLoNcQVgfEnkDw8zJIY4aE4x93P9CyWeiurndAXWSKRdTZsg6N1NhtAVFKRWNHVR5GVTQ6MkWxwtChtTnNJvIpi4e4mUzVf4zP4uNNHEHmwedRQLEJHLre3iZ7wg7L+qfqfmn7+zWNgl133BpvVB8xd5MSJn7aG65GS8Vik5ORtUNynIivP6m/o7k7XvGH66V43VrVr0T8/+MI2ZWVNJfDmIOIVwA8IWBfPLsoTsEePm+kXAX8TE79qNuEwDSDv71tLOrdMLgsfNCr2TqchJ/dx1SrP9GXC2FmR+PZ6zsTNb8dgotahITn6zqOj4Dmsn8hNrncgSHLsOMDKjyVOfuEQAlaohxnyIyABTJDepK6yZ+1GeI0v/RvMCVCkdx2KELfD/2T6kOR0CtYzsDLhdkSs87SE/4SJAh+ZhbIXoYeL2kWBXGcRjASCLNzSxFWeM3sSQeJODgdip+8puHo/qtv3HG5Nh/ClbqDzy/9CqtR1yY4CiH/ERyDGT5doP2dn4N+KGkGn/M6j40u+RNbYIGdvPYXxEMGT2c0KYaR7FiJMdQrKtHBzdzdZyc+8A8ZBojfEzzETlXHkCeSGeFhuZ0=
