language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
before_script:
- cd client
- yarn install
deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-frontend
  api_key:
    secure: Co99UU9fmtPPtPx4PqHVC1rOIa3FoLhQUEFKV7HZroQc4HTpF0C+FU4xEWPW2G+13U2FLzjuua6knxfvfjhDN3Mw1RvrSEznFEmNr067bxp4nIBAXRcB1fxXVbl9riWIxl1yQkwiwEcuqYs3aqvLysvZx2rQGxeGGDwfu3DQSQ6LIR5pHoPXchQfqJhHQp9KwCqgpmS9XpgtJ7XjLJO45VM6mr30MuSd3AVQxRz4fZylN/cPo94MxBnU7TLxOex1qEDry3M+sxQc3mLssb/FXLY39l1x2eGYwV/nrgKDifKK6PIlxfPq5bjmmvK7RGyXu/bw94OJI9cVWnKDZvo/Uvz4bPeydRVV3esE8/C+P18f9Aqty6X2aFT3pYMiScBmQv7Pi7MEmPqcr5yG5qKZt57LmWtHksZOGfGQKysg8DXJWfz0oq8+Rlhzae+Jiua3qwRfMj951kgyrIcEl6wBXEZKw4TI4joPUH2/BeuljRlnO0fZZE/H2sFXcZkindJYh1WOW6LZr4NPJvVsr+iyDipe4PCkCM9q+GaIlAjqMlr71f5D3O3hYmgc+ZyaHLZDVl7voF4Ly6O0zUeihO/Nf6uMPNhALBh8ejCkcKmJwr5uoYk5B/+Nt2kyH5kEcpDCo7zIPYaewqdp0mJwt870UP6RS527NYb/6cQqKndlfeE=
