language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
before_script:
- cd client
- yarn install
deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-frontend
  api_key:
    secure: jjNeRNM09o/7s5d76g8M9mWunfhhc5MU6fCiSA7MNUxZzlrPIXRAi9j28I677vdXVrGtHAtzDYoAmF6XbucXKp6Vp4fYVADbjlxRfqZUlvTYhtWkowoJQP+EVB/W7rue1c8pDVskI30FKC0y0SUBZUUrQXfffcSWZyv6bClaHmseRcFUJZcPzMS0H0OdwSsKI3LXIJs353CAeiWTzja3Eezy8dIjNL1/09lRuSGdcoQNiNL4UNZHHHiJH7inS0w+hWl5kmc+0tqu2CZ9FxHiuImZmtEOLi4uW4k/hdB4Id4DJ6PYI1zhNWJp0EocoU0R3ZOPhEGTxP8yzGVr8JwC+jAx9qVceofZPcEqAlhVZH7/sZcHdLumBYs505sef+Z8ntoLHoV305rANApglj+ihKVBsbjAt9mrP4sw6kwPUsSRgc406s22pdW7yBQHwFnv2s2etGudJBbNgWTWA6qXJcXvRxd+6Q2LOhJYa9f93l42av1S22hvEcuSGZiYn7+yGfEtp+DRRa4QdpMsbPP6Sk5bslORn0Pm/dXsMGiyxbpvZpLh+VxxfGDtFyDpP84JjoMTCrl5fsPKDq/P5jFSSWBORPhOC4NxeU2eKHJWKuhVr8or2TgC3MdLujTtNM6CWZIorIT0bYlun4JdrQdFsUKrAZSLhRCghyC2RLBsIpQ=
