language: node_js
node_js:
  - 10
  
cache:
  directories:
    - node_modules

before_script:
  - cd client
  - npm install

deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-frontend
  api_key:
    secure: kc5ZJRABAhnMh+CFRJZp8TUp2us5LsVjhMoSE+IgOszyc1zBIUcpEzDP1ldMM5JA1WAe6kaiavICSjHGvPvTiECYUr3jr9dOHYgYvw+IXAs7R9Vg0qNXIJydLKaDTCvN6W+OH5nSkDUkktluoafEYSDUqdBoy/J52m+/YYfAgBjJQS6SnhL3LtXHwE2eD5DCsrKVBNgj1NCvYbj2v5GR+yRujHyBWPdt0ehw6sj6S/JE0CkBXUu4EXx7Hc1Xnkys6B68xIX6kdwVDu02qRd09ORYme/jxBW2tyq5oKw2/67M83XB9lPPiotfF+7N51Hc3D5oGGN4GJHcFNH5gvEJlzEywPIbnggqU5ZGC4HJPocJ3q3XPvWtt/NkUbcMKehEfXI8+PuWRr/RkeBrxjwbP3lhUWlZKayV8lwGCCHZEAuhx1upB+Z4ESjJWV8dfIETo4UUqWlgC/Kge3NwDA+mV94qegpuntIDJA1e9C3iCXYt/e8iE0Qgfo6GYFEt+TkembXQ1yrfz1pYHhmBBzOzztxDb3RNmy0YeiliTTGVxgy2bPVviJb3pnpVf/w1hnhq7f7oxO/tAuuVjCqSX5AUfn35yFPLWjUDluLyt/F5yIJfglRM1ChK7CA6BHU2wWbdOfGpvyw9c7wEkXQglrePp241mRRmLAck3oAaYLLykGM=
