language: node_js

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-frontend
  api_key:
    secure: gi0apvQOEnD4/2QHKJ//9C6+wd6FxjFlfOWPchOXeEo20LK5lQSfwLpyuf/hgNVAJF1IohnlYkFH2cpGYif4jAAur6e+LQDRz05mRpbHUmoF6Zhu/w83R1yKxxzaGdiDqrIO4buOgDOt+8xBerslBcusi9FszEmkClS4ogblxec8mWVnHO8pzq0a8RD3mz7m3hTx/zmCVFuTtem5cy6JjqvuEGanx6lD59ZhLjxOBa1UcrJy5onUXjYwd+blZhpeFPRj0+JJZpwMFCcifCYz5IHLp6/9rapCBQCoK05qp0lmmrwBEOnTJ0tzLu8XCz9Vl3W1uJi67D7zh2iP57dZKGlPcz7zN4MROj/+zQzdI712dLpIHw0C0aP2mSTljX36i2387hGtrRJJJei9vq5Gmro5RV/v+IeO8IJjL8HC9q4+pEyEQvEP8mWRVJZYQHa+eo0rxu8TKslZFzgkvgLvqTblznDvDeomToK1Qkv7fqybyv1b+CcRcJYlVxbtO2qsoU7AbCjFfhnkB50t+dV1wgbjihjTsRvIS4ESXGKwp3PqmN1kMZXP8ged/PoWbGbtFRKUGTXpWnmflc/1ACDRBw/iUxTRJMejAtEPBUKAFkSWCvyszS9fYfh2qEXb7mqjDlc88aTB2Bpu0qgsyjx7K6y9t18rp5nqloHQchzfbmM=