language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
before_script:
- cd client
- yarn install
deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-frontend
  api_key:
    secure: o03miChuL1+DIqg/1HIsPzTD7Fau/1H65D5gF/kG035oGMJVMTPpSYI7K0PzRZ6zDAk0ykt0it5+u/wSLfvVhMVEh6TRqF2DjepkrOpVJgRrEJN6sio1fcNCIgHD84DuARMnoExMIWHu2mb74bEHo3QL+l8tP5kxIdExZ/e5/BL07dxQNJvLc8E6zvBb7tgs2kw7XpkffnBn6VEGbc7cT2JM2JbMoo9fjGAzvmyrI1PfxcdICV4609a+NImMg5jV/NbcfT3+3IC9fY7OkRT4IoPd/Zt/k01C1Wlqj9nZmcqyH5PTFPzhquajoOpGVXiwhiWZgy+djqQ8t+luWaACU3cR4IsnpwCzf0N67nn6RMWmBA4pFG8/q2pomzjat2blll6raCVBEo9V/WHih7bROrjSOjBc6KAWuePn+KUfdPApcSTUKPlUdFsAxjeN3wZXYvdEs8dxj1hknSQUY2F9HRsC4079hL9oiHPK4xx/bg1hi13gecn4d81jdE5LFOPbdvko08jZXMyhLRwkw6egnD/lUTvEr45QBo51wFyBuIf1ORH4UKlQMMicbWttpQrFYKgqkZHc5Ho/2bgA597Rm6UlIanuVN6tX4Dq6onqw7pE5Qjo2/3Z237FrddpPJimn6U/RQvTPWnnikzcp2x+bNJUmo27lUvysaYwqdukVfY=
